name: preview
on:
  pull_request:
    branches:
      - dev
      - main
    types: [opened, edited, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install
        run: npm ci
      - name: Test
        run: npm test
      - name: Coverage
        uses: codecov/codecov-action@v1
      - name: Build Docs
        run: npm run build:docs
      - name: Build Storybook
        run: npm run build:storybook
      - name: Deploy Doc Preview to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './website/react-magma-docs/public'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: false
          alias: docs-preview-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - name: Deploy Storybook to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './storybook-static'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: false
          alias: storybook-preview-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
